GET http://localhost:4000/posts 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUm95Y2UiLCJpYXQiOjE2Njk2NDQ1NjEsImV4cCI6MTY2OTY0NDU3Nn0.kB0jfmuYvL5D5zijlzPens8GUbjpN2uZgwOsre_KhmM

###

DELETE http://localhost:4000/logout 
Content-Type: application/json

{
"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUm95Y2UiLCJpYXQiOjE2Njk2NDQ1NjEsImV4cCI6MTY2OTY0NDU3Nn0.kB0jfmuYvL5D5zijlzPens8GUbjpN2uZgwOsre_KhmM"
}

###

POST http://localhost:4000/token 
Content-Type: application/json

{
"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUm95Y2UiLCJpYXQiOjE2Njk2NDQ1NTB9.-7qgX3gWZGNvZdIxK5cwXiC58_9Hn3mPxDJsqt2cdqA"
}

###

POST http://localhost:4000/login 
Content-Type: application/json

{
"username": "Royce"
}
